# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aee7e5277b4591e846792d97144d0b16a29d945b181aea215ed2d29b9064b663d69d5c6bb81a1b622fe695bf12355fb3cb1ae5a457e7e00e760438cdeb04b8f7
  database:
    :host: localhost
    :name: fake_development
    :username: root
    :password: qwerty

test:
  secret_key_base: b4d84c54670aa4b9cd5cd56b88f5ec2c54c804a7059c3a88ef574c15d074786692c8228cb5104bf99cd12b56279695294247d49cbfac210221d11adaf709428b
  database:
    :host: localhost
    :name: fake_test
    :username: root
    :password: qwerty
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  database:
    :host: localhost
    :name: fake_production
    :username: root
    :password: qwerty
